sudo: false

language: node_js

addons:
  code_climate:
    repo_token: 2abac2aeeaecbafa25618c0a62936530b69dbda54d337685290821966189ce63

node_js:
  - 8
  - 6
  - 4

before_install:
  - npm config set spin false
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
  - node -v
  - npm -v

before_script: greenkeeper-lockfile-update

script:
  - npm run test-cov

after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run clean
  - greenkeeper-lockfile-upload
