environment:
  matrix:
    - node_version: "8"
    - node_version: "6"
    - node_version: "4"

skip_tags: true

version: "{build}"

build: off

clone_depth: 10

matrix:
  fast_finish: true

cache:
 - node_modules
 - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:node_version
  - choco install -i yarn
  - node --version
  - npm --version
  - yarn --version
  - appveyor-retry yarn install

test_script:
  - cmd: yarn test
