init:
  - git config --global core.autocrlf input

environment:
  matrix:
  - nodejs_version: "8"
  - nodejs_version: "6"
  - nodejs_version: "4"

skip_tags: true

version: "{build}"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - appveyor-retry npm install

test_script:
  - cmd: npm run test
